//================================================================
//  PROGRAMMER   : CHEN, KE-HAN 
//  DATE         : 2018-09-25
//  FILENAME     : HW01AB07611042.CPP 
//  DESCRIPTION  : Draw a cat 
//================================================================
#include <iostream>
using namespace std;

int     main()
{
        cout << "    /\\_____/\\ " << endl;
        cout << "   /  O   O  \\ " << endl;
        cout << "  ( ==  ^  == ) " << endl;
        cout << "   )         ( " << endl;
        cout << "  (  NTU BIME ) " << endl;
        cout << " ( (  )   (  ) ) " << endl;
        cout << "(__(__)___(__)__) " << endl;

        return 0;
}

